minimumReleaseAgeExclude:
  - '@fumadocs/base-ui@16.11.3'
  - '@fumadocs/tailwind@0.1.1'
  - fumadocs-core@16.11.3
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
  - unrs-resolver
