//! Coherence-safe primitives for derived typed pages and props.

use crate::{PendingPage, props::PendingProp};
use std::{marker::PhantomData, ops::Deref};

/// A statically known Inertia component name.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct Component(&'static str);

impl Component {
    /// Creates a component name.
    pub const fn new(name: &'static str) -> Self {
        Self(name)
    }
    /// Returns the component string.
    pub const fn as_str(self) -> &'static str {
        self.0
    }
}

impl Deref for Component {
    type Target = str;
    fn deref(&self) -> &Self::Target {
        self.0
    }
}

/// A component-qualified, typed top-level prop name.
#[derive(Debug, PartialEq, Eq, Hash)]
pub struct PropKey<T> {
    component: Component,
    name: &'static str,
    marker: PhantomData<fn() -> T>,
}

impl<T> Copy for PropKey<T> {}

impl<T> Clone for PropKey<T> {
    fn clone(&self) -> Self {
        *self
    }
}

impl<T> PropKey<T> {
    /// Creates a typed prop key.
    pub const fn new(component: Component, name: &'static str) -> Self {
        Self {
            component,
            name,
            marker: PhantomData,
        }
    }
    /// Returns the owning component.
    pub const fn component(self) -> Component {
        self.component
    }
    /// Returns the serialized top-level prop name.
    pub const fn name(self) -> &'static str {
        self.name
    }
}

/// Static page-level response flags generated by `InertiaPage`.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct PageOptions {
    encrypt_history: bool,
    clear_history: bool,
    preserve_fragment: bool,
}

impl PageOptions {
    /// Creates empty page options.
    pub const fn new() -> Self {
        Self {
            encrypt_history: false,
            clear_history: false,
            preserve_fragment: false,
        }
    }
    /// Enables encrypted history.
    pub const fn encrypt_history(mut self) -> Self {
        self.encrypt_history = true;
        self
    }
    /// Enables clearing history.
    pub const fn clear_history(mut self) -> Self {
        self.clear_history = true;
        self
    }
    /// Enables fragment preservation.
    pub const fn preserve_fragment(mut self) -> Self {
        self.preserve_fragment = true;
        self
    }
    pub(crate) const fn encrypt_history_enabled(self) -> bool {
        self.encrypt_history
    }
    pub(crate) const fn clear_history_enabled(self) -> bool {
        self.clear_history
    }
    pub(crate) const fn preserve_fragment_enabled(self) -> bool {
        self.preserve_fragment
    }
}

/// Field-by-field pending props produced by derives.
#[doc(hidden)]
pub struct Props(Vec<PendingProp>);

impl Props {
    /// Creates an empty derived-props collection.
    #[doc(hidden)]
    pub fn new() -> Self {
        Self(Vec::new())
    }
    /// Adds one erased field generated by a derive.
    #[doc(hidden)]
    pub fn push(&mut self, prop: PendingProp) {
        self.0.push(prop);
    }
    pub(crate) fn into_inner(self) -> Vec<PendingProp> {
        self.0
    }
}

impl Default for Props {
    fn default() -> Self {
        Self::new()
    }
}

/// Converts a derived struct field-by-field without overlapping legacy eager props.
pub trait IntoInertiaProps: Send + 'static {
    /// Converts this value into pending prop entries.
    fn into_inertia_props(self) -> Props;
}

/// Production typed-page boundary used by the derive.
pub trait InertiaPage: Send + 'static {
    /// Statically known frontend component.
    const COMPONENT: Component;
    /// Converts the typed page into the request-local pending response.
    fn into_pending_page(self) -> PendingPage;
    /// Returns static page-level flags.
    fn options() -> PageOptions {
        PageOptions::new()
    }
}

impl PendingPage {
    /// Constructs a typed pending page from generated props and options.
    #[doc(hidden)]
    pub fn from_typed(component: Component, props: Props, options: PageOptions) -> Self {
        Self {
            component: component.as_str().to_owned(),
            props: props.into_inner(),
            encrypt_history: options.encrypt_history_enabled(),
            clear_history: options.clear_history_enabled(),
            preserve_fragment: options.preserve_fragment_enabled(),
            flash: serde_json::Map::new(),
            status: http::StatusCode::OK,
        }
    }
}
