use super::{AssetTags, HeadMarkup, MountMarkup, RootContext, RootView};

/// Trusted Inertia values supplied to an Askama root template.
///
/// Application values remain part of the application's own typed Askama
/// template. This context contains only the document fragments generated by
/// inertia-axum and optional root metadata.
#[derive(Clone, Copy)]
pub struct AskamaRootContext<'a> {
    /// Pre-rendered asset tags from the configured asset provider.
    pub assets: &'a AssetTags,
    /// Trusted head markup returned by the SSR backend.
    pub head: &'a HeadMarkup,
    /// The generated CSR or SSR Inertia application mount.
    pub mount: &'a MountMarkup,
    /// Whether SSR returned at least one head fragment.
    pub has_ssr_head: bool,
    /// Optional root-document title.
    pub title: Option<&'a str>,
    /// Optional document locale.
    pub locale: Option<&'a str>,
    /// Optional content-security-policy nonce.
    pub nonce: Option<&'a str>,
}

impl<'a> From<RootContext<'a>> for AskamaRootContext<'a> {
    fn from(context: RootContext<'a>) -> Self {
        let RootContext {
            title,
            locale,
            assets,
            head,
            mount,
            nonce,
        } = context;

        Self {
            assets,
            head,
            mount,
            has_ssr_head: !head.as_str().is_empty(),
            title,
            locale,
            nonce,
        }
    }
}

/// Creates the typed Askama template used for the application's root document.
///
/// The generated template may borrow both application configuration and the
/// request-local Inertia document fragments.
pub trait AskamaRoot: Clone + Send + Sync + 'static {
    /// The concrete Askama template generated for one root render.
    type Template<'a>: ::askama::Template
    where
        Self: 'a;

    /// Creates the template for the current initial-page response.
    fn template<'a>(&'a self, context: AskamaRootContext<'a>) -> Self::Template<'a>;
}

#[derive(Clone)]
pub(crate) struct AskamaRootView<R> {
    root: R,
}

impl<R> AskamaRootView<R> {
    pub(crate) fn new(root: R) -> Self {
        Self { root }
    }
}

impl<R> RootView for AskamaRootView<R>
where
    R: AskamaRoot,
{
    type Error = ::askama::Error;

    fn render(&self, context: RootContext<'_>) -> Result<String, Self::Error> {
        let fragment_len = context.fragment_len();
        let template = self.root.template(context.into());

        render_template(&template, fragment_len)
    }
}

fn render_template<T>(template: &T, fragment_len: usize) -> ::askama::Result<String>
where
    T: ::askama::Template,
{
    let capacity = T::SIZE_HINT.saturating_add(fragment_len);
    let mut output = String::with_capacity(capacity);

    template.render_into(&mut output)?;

    Ok(output)
}
