use super::{AssetTags, HeadMarkup, MountMarkup, RootContext, RootView};

/// Trusted Inertia values supplied to an Askama root template.
///
/// Application values remain part of the application's own typed Askama
/// template. This context contains only the document fragments generated by
/// inertia-axum and optional root metadata.
#[derive(Clone, Copy)]
pub struct AskamaRootContext<'a> {
    /// Trusted, pre-rendered asset tags from the configured asset provider.
    ///
    /// This value is generated by `inertia-axum`. In an HTML Askama template, render it with `|safe`. Do not apply `|safe` broadly to application or user-provided values.
    pub assets: &'a AssetTags,
    /// Trusted head markup returned by the SSR backend.
    ///
    /// This value is generated by `inertia-axum`. In an HTML Askama template, render it with `|safe`. Do not apply `|safe` broadly to application or user-provided values.
    pub head: &'a HeadMarkup,
    /// Trusted generated CSR or SSR Inertia application mount markup.
    ///
    /// This value is generated by `inertia-axum`. In an HTML Askama template, render it with `|safe`. Do not apply `|safe` broadly to application or user-provided values.
    pub mount: &'a MountMarkup,
    /// Whether SSR returned at least one head fragment; this is not markup.
    pub has_ssr_head: bool,
    /// Optional root-document title; this is untrusted text, not markup.
    pub title: Option<&'a str>,
    /// Optional document locale; this is untrusted text, not markup.
    pub locale: Option<&'a str>,
    /// Optional content-security-policy nonce; this is untrusted text, not markup.
    pub nonce: Option<&'a str>,
}

impl<'a> From<RootContext<'a>> for AskamaRootContext<'a> {
    fn from(context: RootContext<'a>) -> Self {
        let RootContext {
            title,
            locale,
            assets,
            head,
            mount,
            nonce,
        } = context;

        Self {
            assets,
            head,
            mount,
            has_ssr_head: !head.as_str().is_empty(),
            title,
            locale,
            nonce,
        }
    }
}

/// Creates the typed Askama template used for the application's root document.
///
/// The generated template may borrow both application configuration and the
/// request-local Inertia document fragments.
///
/// # Example
///
/// ```rust
/// use inertia_axum::{
///     AskamaRoot,
///     AskamaRootContext,
///     askama::{self, Template},
/// };
///
/// #[derive(Template)]
/// #[template(
///     source = "\
///         <!doctype html>\
///         <html>\
///           <head>\
///             {{ inertia.assets|safe }}\
///             {{ inertia.head|safe }}\
///           </head>\
///           <body>\
///             {{ inertia.mount|safe }}\
///           </body>\
///         </html>",
///     ext = "html",
///     askama = askama,
/// )]
/// struct TemplateRoot<'a> {
///     inertia: AskamaRootContext<'a>,
/// }
///
/// #[derive(Clone, Copy)]
/// struct Root;
///
/// impl AskamaRoot for Root {
///     type Template<'a> = TemplateRoot<'a>;
///
///     fn template<'a>(
///         &'a self,
///         inertia: AskamaRootContext<'a>,
///     ) -> Self::Template<'a> {
///         TemplateRoot { inertia }
///     }
/// }
/// ```
pub trait AskamaRoot: Clone + Send + Sync + 'static {
    /// The concrete Askama template generated for one root render.
    type Template<'a>: ::askama::Template
    where
        Self: 'a;

    /// Creates the template for the current initial-page response.
    fn template<'a>(&'a self, context: AskamaRootContext<'a>) -> Self::Template<'a>;
}

#[derive(Clone)]
pub(crate) struct AskamaRootView<R> {
    root: R,
}

impl<R> AskamaRootView<R> {
    pub(crate) fn new(root: R) -> Self {
        Self { root }
    }
}

impl<R> RootView for AskamaRootView<R>
where
    R: AskamaRoot,
{
    type Error = ::askama::Error;

    fn render(&self, context: RootContext<'_>) -> Result<String, Self::Error> {
        let fragment_len = context.fragment_len();
        let template = self.root.template(context.into());

        render_template(&template, fragment_len)
    }
}

fn render_template<T>(template: &T, fragment_len: usize) -> ::askama::Result<String>
where
    T: ::askama::Template,
{
    let capacity = T::SIZE_HINT.saturating_add(fragment_len);
    let mut output = String::with_capacity(capacity);

    template.render_into(&mut output)?;

    Ok(output)
}

#[cfg(all(test, feature = "askama"))]
mod tests {
    use super::*;

    #[derive(::askama::Template)]
    #[template(
        source = "<!doctype html><html><head><title>{{ app_name }}</title>{{ inertia.assets|safe }}{{ inertia.head|safe }}</head><body><p>{{ description }}</p>{{ inertia.mount|safe }}</body></html>",
        ext = "html",
        askama = ::askama
    )]
    struct TestTemplate<'a> {
        inertia: AskamaRootContext<'a>,
        app_name: &'a str,
        description: &'a str,
    }

    #[derive(Clone)]
    struct TestRoot {
        app_name: &'static str,
        description: &'static str,
    }

    impl AskamaRoot for TestRoot {
        type Template<'a> = TestTemplate<'a>;

        fn template<'a>(&'a self, inertia: AskamaRootContext<'a>) -> Self::Template<'a> {
            TestTemplate {
                inertia,
                app_name: self.app_name,
                description: self.description,
            }
        }
    }

    fn render(root: TestRoot, head_markup: &str) -> String {
        let assets = AssetTags::new("<script data-asset></script>".to_owned());
        let head = HeadMarkup::for_test(head_markup);
        let mount = MountMarkup::for_test("<div data-mount></div>");
        RootView::render(
            &AskamaRootView::new(root),
            RootContext::new(&assets, &head, &mount),
        )
        .unwrap()
    }

    #[test]
    fn trusted_inertia_fragments_are_not_escaped() {
        let html = render(
            TestRoot {
                app_name: "Acme",
                description: "Description",
            },
            "<meta data-head>",
        );
        assert!(html.contains("<script data-asset></script>"));
        assert!(html.contains("<meta data-head>"));
        assert!(html.contains("<div data-mount></div>"));
        assert!(!html.contains("&lt;script data-asset"));
    }

    #[test]
    fn application_values_are_html_escaped() {
        let html = render(
            TestRoot {
                app_name: "<Acme>",
                description: "<script>alert(1)</script>",
            },
            "",
        );
        assert!(html.contains("<title>&#60;Acme&#62;</title>"));
        assert!(html.contains("<p>&#60;script&#62;alert(1)&#60;/script&#62;</p>"));
        assert!(!html.contains("<p><script>"));
    }

    #[test]
    fn each_inertia_fragment_is_rendered_once() {
        let html = render(
            TestRoot {
                app_name: "Acme",
                description: "Description",
            },
            "<meta data-head>",
        );
        assert_eq!(html.matches("data-asset").count(), 1);
        assert_eq!(html.matches("data-head").count(), 1);
        assert_eq!(html.matches("data-mount").count(), 1);
    }

    #[test]
    fn csr_context_reports_no_ssr_head() {
        let assets = AssetTags::empty();
        let head = HeadMarkup::empty();
        let mount = MountMarkup::for_test("");
        let context = AskamaRootContext::from(RootContext::new(&assets, &head, &mount));
        assert!(!context.has_ssr_head);
    }

    #[test]
    fn ssr_context_reports_head_content() {
        let assets = AssetTags::empty();
        let head = HeadMarkup::for_test("<title>SSR</title>");
        let mount = MountMarkup::for_test("");
        let context = AskamaRootContext::from(RootContext::new(&assets, &head, &mount));
        assert!(context.has_ssr_head);
    }

    mod filters {
        #[::askama::filter_fn]
        pub fn fail(
            _value: &dyn std::fmt::Display,
            _values: &dyn ::askama::Values,
        ) -> ::askama::Result<String> {
            Err(::askama::Error::custom(std::io::Error::other(
                "test render failure",
            )))
        }
    }

    #[derive(::askama::Template)]
    #[template(source = "{{ value|fail }}", ext = "html", askama = ::askama)]
    struct FallibleTemplate<'a> {
        value: &'a str,
    }

    #[test]
    fn askama_errors_propagate() {
        let error = render_template(&FallibleTemplate { value: "value" }, 0).unwrap_err();
        assert_eq!(error.to_string(), "test render failure");
    }
}
